export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";
export const SET_SERVICES = "SET_SERVICES";
export const SET_SELECTED_SERVICE = "SET_SELECTED_SERVICE";
export const FETCH_SERVICES_START = "FETCH_SERVICES_START";
export const SET_SERVICE_FOR_BOOKING = "SET_SERVICE_FOR_BOOKING";

export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const CREATE_APPOINTMENT_START = "CREATE_APPOINTMENT_START";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const FETCH_APPOINTMENTS_START = "FETCH_APPOINTMENTS_START";
export const FETCH_APPOINTMENTS_SUCCESS = "FETCH_APPOINTMENTS_SUCCESS";
export const FETCH_APPOINTMENTS_FAIL = "FETCH_APPOINTMENTS_FAIL";
export const CLEAR_APPOINTMENTS = "CLEAR_APPOINTMENTS";

export const ADD_USER_DATA_START = "ADD_USER_DATA_START";
export const ADD_USER_DATA_SUCCESS = "ADD_USER_DATA_SUCCESS";
export const ADD_USER_DATA_FAIL = "ADD_USER_DATA_FAIL";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";

export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAIL = "UPDATE_USER_DATA_FAIL";